"""Primitives the criteria layer depends on. Each module is also wrappable as an MCP server (see gate/mcp_servers/)."""

from gate.tools.ai_review import (
    AIReviewFinding,
    AIReviewVerdict,
    parse_ai_review_comment,
    parse_ai_review_findings,
    read_ai_review_verdicts,
)
from gate.tools.chart_overlay import (
    CLUSTER_OVERLAY_REPOS,
    DEFAULT_OVERLAY_ENVS,
    ChartFlipSignal,
    YamlDict,
    any_cluster_overlay_sets_flip,
    evidence_for_flip,
    fetch_overlay_yaml,
    find_overlay_pr_refs,
    parse_chart_flip_signals,
)
from gate.tools.coverage import CoverageReport, read_coverage_from_pr_comments, read_coverage_threshold
from gate.tools.end2end_gate import (
    End2EndFailure,
    End2EndTest,
    build_end2end_failure,
    classify_end2end_failure,
    extract_failed_tests,
    fetch_end2end_failure,
    is_end2end_gate,
    is_end2end_ui_gate,
    parse_results_json_from_log,
)
from gate.tools.parsers import (
    ARTEFACT_PARSERS,
    GATE_TO_ARTEFACT_TYPE,
    Finding,
    GateFailure,
    normalise_severity,
    parse_coverage_json,
    parse_gate_artefact,
    parse_gate_artefact_auto,
    parse_govulncheck_json,
    parse_junit_xml,
    parse_playwright_json,
    parse_results_json,
    parse_sarif,
    parse_trivy_json,
    resolve_artefact_type,
)
from gate.tools.pipelines import PipelineCheck, list_pr_checks
from gate.tools.playwright_artifacts import (
    Artifact,
    PlaywrightRun,
    download_artifact,
    head_artifact,
    is_fragile_text_selector,
    read_playwright_runs,
)
from gate.tools.playwright_specs import SpecCoverage, inventory_specs, parse_spec
from gate.tools.pr_context import PRContext, fetch_pr_commit_messages, load_pr_context
from gate.tools.pr_diff import added_files, added_lines, fetch_pr_diff
from gate.tools.repo_factory import (
    KNOWN_TEMPLATES,
    RenameReport,
    create_repo,
    name_variants,
    open_scaffold_pr,
    push_main,
    rename_tree,
    render_template,
    resolve_template,
    scaffold,
    scaffold_working_tree,
)
from gate.tools.security_claim import (
    SecurityClaim,
    evidence_for_claim,
    find_manifest_refs,
    has_in_diff_evidence,
    manifest_exists_at_ref,
    parse_security_claims,
)
from gate.tools.source_config import (
    SOURCE_CONFIG_PATH,
    add_repo_to_source_config,
    is_registered,
    register_source_config,
    source_config_entry,
)
from gate.tools.spec_suggester import (
    SpecSuggestion,
    is_anthropic_key_present,
    suggest_spec,
)
from gate.tools.triggers import (
    Trigger,
    angular_template_consumers,
    diff_triggers,
    fetch_triggers_yaml,
    go_service_template_consumers,
    golden_template_for,
    parse_triggers_yaml,
)
from gate.tools.ui_surface_diff import (
    UISurfaceDelta,
    compute_ui_surface_delta,
    selectors_from_added_lines,
)
from gate.tools.video_review import (
    Prerequisites,
    VideoVerdict,
    check_prerequisites,
    extract_frames,
    review_video,
)

__all__ = [
    'PRContext',
    'fetch_pr_commit_messages',
    'load_pr_context',
    'PipelineCheck',
    'list_pr_checks',
    'CoverageReport',
    'read_coverage_threshold',
    'read_coverage_from_pr_comments',
    'AIReviewFinding',
    'AIReviewVerdict',
    'parse_ai_review_comment',
    'parse_ai_review_findings',
    'read_ai_review_verdicts',
    'CLUSTER_OVERLAY_REPOS',
    'DEFAULT_OVERLAY_ENVS',
    'ChartFlipSignal',
    'YamlDict',
    'any_cluster_overlay_sets_flip',
    'evidence_for_flip',
    'fetch_overlay_yaml',
    'find_overlay_pr_refs',
    'parse_chart_flip_signals',
    'End2EndFailure',
    'End2EndTest',
    'build_end2end_failure',
    'classify_end2end_failure',
    'extract_failed_tests',
    'fetch_end2end_failure',
    'is_end2end_gate',
    'is_end2end_ui_gate',
    'parse_results_json_from_log',
    'fetch_pr_diff',
    'added_files',
    'added_lines',
    'Artifact',
    'PlaywrightRun',
    'read_playwright_runs',
    'download_artifact',
    'head_artifact',
    'is_fragile_text_selector',
    'VideoVerdict',
    'Prerequisites',
    'check_prerequisites',
    'extract_frames',
    'review_video',
    'Trigger',
    'parse_triggers_yaml',
    'fetch_triggers_yaml',
    'golden_template_for',
    'angular_template_consumers',
    'go_service_template_consumers',
    'diff_triggers',
    'UISurfaceDelta',
    'compute_ui_surface_delta',
    'selectors_from_added_lines',
    'SpecCoverage',
    'inventory_specs',
    'parse_spec',
    'SpecSuggestion',
    'suggest_spec',
    'is_anthropic_key_present',
    'KNOWN_TEMPLATES',
    'RenameReport',
    'create_repo',
    'name_variants',
    'open_scaffold_pr',
    'push_main',
    'render_template',
    'rename_tree',
    'resolve_template',
    'scaffold',
    'scaffold_working_tree',
    'SOURCE_CONFIG_PATH',
    'add_repo_to_source_config',
    'is_registered',
    'register_source_config',
    'source_config_entry',
    'SecurityClaim',
    'evidence_for_claim',
    'find_manifest_refs',
    'has_in_diff_evidence',
    'manifest_exists_at_ref',
    'parse_security_claims',
    # v6p0.6 step 1 — structured artefact parsers + dispatcher
    'ARTEFACT_PARSERS',
    'Finding',
    'GATE_TO_ARTEFACT_TYPE',
    'GateFailure',
    'normalise_severity',
    'parse_coverage_json',
    'parse_gate_artefact',
    'parse_gate_artefact_auto',
    'parse_govulncheck_json',
    'parse_junit_xml',
    'parse_playwright_json',
    'parse_results_json',
    'parse_sarif',
    'parse_trivy_json',
    'resolve_artefact_type',
]
