"""Deterministic repo scaffolding — clone a language service-template and rename it.

The repo-factory creates a new service repo from one of the ``leartech-<lang>-service-
template`` repos. The rename is a LITERAL string substitution (NOT an LLM grep/replace):
every template carries its own kebab name (e.g. ``leartech-go-service-template``) as the
placeholder, so scaffolding = replace that name (and its snake_case DB variant) with the
new service name everywhere, plus rename the ``charts/<template-name>/`` directory. The
result is byte-for-byte reproducible — see memory project_repo_factory_init.

Grounded against the actual templates (2026-07-23): the ONLY placeholders are the kebab
name and its snake_case form; there is NO ``LEARTECH_*`` env-prefix placeholder. The Go
module path (``github.com/mikelear/leartech-go-service-template``), the image repo
(``ghcr.io/mikelear/leartech-angular-service-template``), and staging hostnames all
*contain* the kebab name, so the single kebab substitution rewrites them too. Lock files
(package-lock.json) and generated docs (docs/swagger.*) are regenerated by the language
toolchain on first build — out of scope for the literal rename.
"""

from __future__ import annotations

import os
import shutil
from dataclasses import dataclass
from pathlib import Path

from gate.tools._subprocess import default_org, run

# Language key -> the template's own kebab name (which is BOTH the GitHub repo short name
# and the in-tree placeholder string). Mirrors the templates referenced by
# gate/tools/triggers.py GOLDEN_TEMPLATE_FOR.
KNOWN_TEMPLATES: dict[str, str] = {
    'go': 'leartech-go-service-template',
    'angular': 'leartech-angular-service-template',
    'rust': 'leartech-rust-service-template',
    'dotnet': 'leartech-dotnet-service-template',
}

# Directories never touched by the content pass or the rename pass: VCS metadata and
# toolchain-generated trees. These carry no placeholders we own and can be huge/binary.
SKIP_DIRS: frozenset[str] = frozenset({'.git', 'node_modules', 'dist', '__pycache__', '.angular', 'bin', 'obj'})

# Bytes we sniff to decide text-vs-binary; a NUL byte in the first chunk => binary => skip.
_SNIFF_BYTES = 8192


@dataclass(frozen=True)
class RenameReport:
    """What a rename pass changed — used to assert determinism + for observability."""

    files_changed: tuple[str, ...]  # repo-relative paths whose CONTENTS changed
    dirs_renamed: tuple[tuple[str, str], ...]  # (old_rel, new_rel) path renames
    occurrences: int  # total literal substitutions applied across all files


def name_variants(old_name: str, new_name: str) -> list[tuple[str, str]]:
    """Ordered ``(old, new)`` literal pairs to substitute, most-specific first.

    snake_case (``leartech_go_service_template`` -> DB name) is applied before kebab so
    the two never race — they share no characters (``_`` vs ``-``), so order is not
    strictly required, but keeping the more-specific form first is defensive. The kebab
    pair alone rewrites the module path / image repo / hostnames because they contain it.
    """
    return [
        (old_name.replace('-', '_'), new_name.replace('-', '_')),
        (old_name, new_name),
    ]


def _is_text_file(path: Path) -> bool:
    """True if the file looks like text (no NUL byte in the first chunk). Missing/unreadable => False."""
    try:
        with path.open('rb') as fh:
            return b'\x00' not in fh.read(_SNIFF_BYTES)
    except OSError:
        return False


def rename_tree(root: str | os.PathLike[str], old_name: str, new_name: str) -> RenameReport:
    """Rewrite ``old_name`` -> ``new_name`` (kebab + snake variants) across a cloned template.

    Two passes over ``root`` (skipping SKIP_DIRS):
      1. CONTENT — every text file: apply the literal substitutions, write back if changed.
      2. RENAME  — bottom-up, any file/dir whose basename contains ``old_name``: rename it
         (handles ``charts/<template-name>/`` and any similarly-named path component).

    Pure filesystem mutation — no git, no network — so it is fully unit-testable against a
    fixture tree. Returns a RenameReport for determinism assertions + logging.
    """
    root_path = Path(root)
    variants = name_variants(old_name, new_name)

    files_changed: list[str] = []
    occurrences = 0

    # --- Pass 1: file contents ---
    for dirpath, dirnames, filenames in os.walk(root_path):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for fname in filenames:
            fpath = Path(dirpath) / fname
            if not _is_text_file(fpath):
                continue
            original = fpath.read_text(encoding='utf-8', errors='surrogateescape')
            updated = original
            hits = 0
            for old, new in variants:
                if old in updated:
                    hits += updated.count(old)
                    updated = updated.replace(old, new)
            if updated != original:
                fpath.write_text(updated, encoding='utf-8', errors='surrogateescape')
                files_changed.append(str(fpath.relative_to(root_path)))
                occurrences += hits

    # --- Pass 2: path renames (bottom-up so parent renames don't invalidate child paths) ---
    dirs_renamed: list[tuple[str, str]] = []
    for dirpath, dirnames, filenames in os.walk(root_path, topdown=False):
        if any(part in SKIP_DIRS for part in Path(dirpath).relative_to(root_path).parts):
            continue
        for name in (*filenames, *dirnames):
            if old_name not in name:
                continue
            src = Path(dirpath) / name
            dst = Path(dirpath) / name.replace(old_name, new_name)
            old_rel = str(src.relative_to(root_path))
            os.rename(src, dst)
            dirs_renamed.append((old_rel, str(dst.relative_to(root_path))))

    return RenameReport(
        files_changed=tuple(sorted(files_changed)),
        dirs_renamed=tuple(dirs_renamed),
        occurrences=occurrences,
    )


def resolve_template(template: str) -> tuple[str, str]:
    """Resolve a template argument to ``(repo, placeholder)``.

    Accepts a language key (``go``/``angular``/...), a bare template repo name
    (``leartech-go-service-template``), or an ``owner/repo`` slug. Returns the fully
    qualified repo to clone and the in-tree placeholder string to replace.
    """
    org = default_org()
    if template in KNOWN_TEMPLATES:
        short = KNOWN_TEMPLATES[template]
        return f'{org}/{short}', short
    short = template.split('/')[-1]
    repo = template if '/' in template else f'{org}/{template}'
    return repo, short


def _qualify(repo: str, org: str | None = None) -> str:
    return repo if '/' in repo else f'{org or default_org()}/{repo}'


def render_template(
    template: str,
    new_name: str,
    dest: str | os.PathLike[str],
    *,
    ref: str = 'main',
    placeholder: str | None = None,
) -> RenameReport:
    """Materialise a template into ``dest`` (must not exist) and rename it deterministically.

    ``template`` may be a language key (``go``/``angular``/...), an ``owner/repo`` slug, or a
    path to a LOCAL template directory. A local dir is COPIED (enables offline tests + local
    template dev); anything else is cloned. ``.git`` is never carried over — the rename tool
    produces content only; git identity is the caller's job. Returns the RenameReport so
    determinism can be asserted (see tests). ``placeholder`` overrides the inferred old name
    (defaults to the local dir basename, or the template repo's short name).
    """
    dest_path = Path(dest)
    src = Path(template)
    if src.exists() and src.is_dir():
        shutil.copytree(src, dest_path, ignore=shutil.ignore_patterns('.git'))
        old_name = placeholder or src.name
    else:
        repo, short = resolve_template(template)
        run(['git', 'clone', '--depth=1', '--branch', ref, f'https://github.com/{repo}.git', str(dest_path)])
        git_dir = dest_path / '.git'
        if git_dir.exists():
            shutil.rmtree(git_dir)
        old_name = placeholder or short
    return rename_tree(dest_path, old_name, new_name)


def scaffold(
    *,
    template: str,
    new_name: str,
    dest: str | os.PathLike[str],
    ref: str = 'main',
) -> RenameReport:
    """Render a template into ``dest`` and init a FRESH git repo tagged v0.0.1 (no remote).

    The building block for main-push mode: call ``push_main()`` to publish. ``dest`` must
    not already exist.
    """
    report = render_template(template, new_name, dest, ref=ref)
    dest_path = Path(dest)
    run(['git', 'init'], cwd=dest_path)
    run(['git', 'branch', '-m', 'main'], cwd=dest_path)
    run(['git', 'add', '-A'], cwd=dest_path)
    run(['git', 'commit', '-m', f'feat: scaffold {new_name}'], cwd=dest_path)
    run(['git', 'tag', 'v0.0.1'], cwd=dest_path)
    return report


def create_repo(name: str, *, org: str | None = None, private: bool = True, add_readme: bool = True) -> str:
    """``gh repo create`` an EMPTY repo. Returns the ``owner/repo`` slug.

    ``add_readme`` seeds a README so ``main`` exists — required so a later scaffold can be
    opened as a PR (an empty repo has no base ref to PR against — see memory
    feedback_new_repo_bootstrap_needs_smoke_tests). This is the Plan's ``create`` step: the
    repo must exist before source-config registration references it.
    """
    slug = _qualify(name, org)
    args = ['gh', 'repo', 'create', slug, '--private' if private else '--public']
    if add_readme:
        args.append('--add-readme')
    run(args)
    return slug


def push_main(dest: str | os.PathLike[str], target_repo: str) -> None:
    """Push a scaffolded local repo (from ``scaffold()``) to ``target_repo`` main + v0.0.1 tag.

    Main-push mode — for a fresh repo where a preview isn't required. Use ``open_scaffold_pr``
    when the scaffold should run through a PR preview (exercises the Tekton steps).
    """
    slug = _qualify(target_repo)
    dest_path = Path(dest)
    run(['git', 'remote', 'add', 'origin', f'https://github.com/{slug}.git'], cwd=dest_path)
    run(['git', 'push', '-u', 'origin', 'main'], cwd=dest_path)
    run(['git', 'push', 'origin', 'v0.0.1'], cwd=dest_path)


def open_scaffold_pr(
    *,
    template: str,
    new_name: str,
    target_repo: str,
    workdir: str | os.PathLike[str],
    branch: str | None = None,
    title: str | None = None,
    body: str | None = None,
    ref: str = 'main',
) -> str:
    """Scaffold template content onto a NEW branch of an EXISTING repo and open a PR. Returns the PR URL.

    PR mode — the repo-factory's default. ``target_repo`` must already exist with a ``main``
    to branch from (``create_repo(add_readme=True)`` guarantees it) AND be registered in
    source-config first (so Lighthouse gates + a preview fire on the PR). Clones the target,
    overlays the renamed template files (preserving the target's ``.git``), commits on
    ``branch``, pushes, and opens the PR whose preview exercises every Tekton step.
    ``workdir`` must not exist.
    """
    slug = _qualify(target_repo)
    branch = branch or f'scaffold-{new_name}'
    work = Path(workdir)
    rendered = work / 'rendered'
    target = work / 'target'

    render_template(template, new_name, rendered, ref=ref)
    run(['git', 'clone', f'https://github.com/{slug}.git', str(target)])
    # Overlay onto the target clone, keeping its .git so the branch descends from main.
    shutil.copytree(rendered, target, dirs_exist_ok=True, ignore=shutil.ignore_patterns('.git'))

    run(['git', 'checkout', '-b', branch], cwd=target)
    run(['git', 'add', '-A'], cwd=target)
    run(['git', 'commit', '-m', f'feat: scaffold {new_name} from template'], cwd=target)
    run(['git', 'push', '-u', 'origin', branch], cwd=target)
    pr_url = run(
        [
            'gh',
            'pr',
            'create',
            '--repo',
            slug,
            '--head',
            branch,
            '--title',
            title or f'feat: scaffold {new_name} from template',
            '--body',
            body
            or (
                f'Deterministic scaffold of `{new_name}` from its language template '
                f'(gate.tools.repo_factory — literal rename, no LLM grep). The preview '
                f'on this PR exercises every Tekton step before merge.'
            ),
        ],
        cwd=target,
    )
    return pr_url.strip()


def scaffold_working_tree(
    template: str,
    new_name: str,
    workdir: str | os.PathLike[str],
    *,
    ref: str = 'main',
) -> RenameReport:
    """Overlay a template's renamed content INTO an existing git working tree. Returns the report.

    The mechanism for the Plan's scaffold step: the AgentRun init-container has already cloned
    the target repo into ``workdir``; this renders the template (in an isolated temp dir),
    then overlays the renamed files on top — leaving the changes UNCOMMITTED and preserving
    ``.git``, so the agent opens the PR via the ``open_pr`` MCP tool. That publishes
    ``targetPR`` (so the step gates on merge) and its preview exercises the Tekton steps —
    unlike ``open_scaffold_pr`` (which opens the PR itself via ``gh`` and does NOT publish
    ``targetPR`` for the controller to gate on).
    """
    work = Path(workdir)
    _repo, placeholder = resolve_template(template)
    tmp = work.parent / f'.{work.name}-template-render'
    report = render_template(template, new_name, tmp, ref=ref, placeholder=placeholder)
    shutil.copytree(tmp, work, dirs_exist_ok=True, ignore=shutil.ignore_patterns('.git'))
    shutil.rmtree(tmp)
    return report
