"""Render the agent system prompts to docs/agent-system-prompt.md.

The prompt an agent actually receives is assembled at runtime from the JX3 calibration
plus the Python-rendered role prompt, so a change to either alters agent behaviour
without appearing as a readable diff. Committing the assembled result makes every
prompt change show up in the PR that causes it.

Run `python scripts/render_system_prompt.py --write` to regenerate.
"""

from __future__ import annotations

import argparse
import pathlib
import sys

from gate.agent.calibrations import load_jx3_calibration
from gate.agent.initiative_prompt import render_initiative_system_prompt
from gate.agent.system_prompt import REVIEW_SYSTEM_PROMPT

OUTPUT = pathlib.Path('docs/agent-system-prompt.md')


def assemble(role: str) -> str:
    """Assemble the prompt exactly as the runtime does for `role`."""
    blocks: list[str] = [load_jx3_calibration()]
    if role == 'initiative_agent':
        blocks.append(render_initiative_system_prompt(hold=False))
    elif role == 'review_agent':
        blocks.append(REVIEW_SYSTEM_PROMPT)
    return '\n\n---\n\n'.join(blocks)


def render() -> str:
    parts = [
        '# Assembled agent system prompts',
        '',
        'Generated by `scripts/render_system_prompt.py`. Do not hand-edit — change the source',
        '(`gate/agent/calibrations`, `gate/agent/initiative_prompt.py`)',
        'and regenerate. `tests/test_prompt_contract.py` fails when this file is stale, so any',
        'behaviour change reaching an agent is visible in the PR diff.',
        '',
    ]
    for role in ('initiative_agent', 'review_agent'):
        text = assemble(role)
        parts += [
            f'## {role}',
            '',
            f'{len(text)} characters (~{len(text) // 4} tokens per turn).',
            '',
            '````markdown',
            text,
            '````',
            '',
        ]
    return '\n'.join(parts)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--write', action='store_true', help='write the file instead of checking it')
    args = ap.parse_args()
    rendered = render()
    if args.write:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(rendered)
        print(f'wrote {OUTPUT} ({len(rendered)} chars)')
        return 0
    if not OUTPUT.exists() or OUTPUT.read_text() != rendered:
        print(f'{OUTPUT} is stale — run: python scripts/render_system_prompt.py --write', file=sys.stderr)
        return 1
    print(f'{OUTPUT} is current')
    return 0


if __name__ == '__main__':
    sys.exit(main())
